### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by ericf** [unicode-cldr/cldr-json#1]
I see that the JSON packages are published to Bower, could these also be published to npm?

I noticed that each of the repos have `package.json` files, but the problem is the `dependencies` in each package are written such that they require all the package to be published to npm. If you all don't publish to npm, then those dependencies could be updated to use Git URIs pointing to tags on GitHub.

**Comment by tinganho** [comment]
I agree on this. Also CLDR data is mostly used in build tools and therefore doesn't make so much sense to be published on bower.

**Comment by JCEmmons** [comment]
Let me catch my breath here, and then I'll look into it.  I can't think of any reason why we wouldn't want to publish to npm as well.

**Comment by ericf** [comment]
@JCEmmons let us know how we can help devise a release strategy for you so these package can work over npm, and so it can be automated.

**Comment by JCEmmons** [comment]
Thanks for the offer, @ericf , I'll be the first to admit that I'm not terribly knowledgeable when it comes to npm, so please bear with me.   I just finished publishing all the packages to NPM, and they seem to install OK, but I'm not really happy with the results.  For example, cldr-numbers-modern depends on cldr-core. If I "npm install cldr-numbers-modern", the stuff for cldr-core winds up in "node_modules/cldr-numbers-modern/node_modules/cldr-core", which for our purposes probably isn't where we would want it to wind up.

I would like to find out if there is a mechanism in npm whereby I can control where things get installed.  What I would really like to do here is to make it so that all the cldr stuff winds up in the same place upon install, so that I have something like:

<cldr-install-directory>
    <main>
      <en>
         numbers.json ( English from cldr-numbers-modern )
         units.json ( English from cldr-units-modern )
         etc.
      <de>
         numbers.json ( German from cldr-numbers-modern )
         units.json ( German from cldr-units-modern )         
    <supplemental>
        ... The stuff from cldr-core

If that's not possible then at least:

mode_modules
    cldr-core
    cldr-numbers-modern
    cldr-dates-modern
etc. ( things sitting side by side, even if they got there because of a dependency and not because of a direct "npm install" )

Any ideas?

**Comment by ericf** [comment]
`peerDependencies` could be a way to handle this. That would at least put all the packages at the same level and be more like what you'd have in Bower.

**Comment by JCEmmons** [comment]
Thanks, Eric. That appears to be exactly what we're looking for here.  I'll try to incorporate this. See http://unicode.org/cldr/trac/ticket/8301

**Comment by JCEmmons** [comment]
Fixed in 27.0.1
