### ISSUE TITLE
How to download data without packaging system

### ISSUE THREAD

**Issue by GinoPane** [unicode-cldr/cldr-json#10]
Is there currently a way to download cldr data as single archive, like it was in 26 version, for example? For example, I want to download data using my php script. 

Npm resolves installing cldr-data package into downloading of some archives, but how anyone get links to that archives without packaging system?

**Comment by pgolebiowski** [comment]
Yes, that would be very helpful. As for now, to get the fully resolved JSON data automatically, I need to go through multiple repositories, access the `bower.json` files to find patterns in order to find all the actual *data files*. This is a real hassle :disappointed:

Could you please make the CLDR JSON data available in the fully resolved form, available by a single download? When prettified (no spaces) and zipped, that shouldn't be too big. But that would make using this data ***much*** easier.

I'd be very grateful!

**Comment by JCEmmons** [comment]
Please open a ticket in http://unicode.org/cldr/trac to request this.  I can't promise that we will have resources to do this.  However, you should be able to generate the JSON directly using the LDML2JSON conversion utilities included in CLDR's tools.zip.
