### ISSUE TITLE
list of valids? valid pt-BR not there

### ISSUE THREAD

**Issue by ppKrauss** [unicode-cldr/cldr-json#6]
The oficial code `pt-BR` exist as `pt_BR.xml` file at http://www.unicode.org/Public/cldr/latest/core.zip (and [i18ndata.appspot](http://i18ndata.appspot.com/cldr/main/pt_BR?action=browse&depth=1))
but not as record at https://github.com/unicode-cldr/cldr-dates-full/tree/master/main
... ok, because not changes its `pt` root (understanding that "default `pt`" is pt-BR).

There are a  `https://github.com/unicode-cldr/cldr-valid` for check all that have defined `identity`?

**Comment by JCEmmons** [comment]
Please see http://cldr.unicode.org/development/development-process/design-proposals/json-packaging in the 3rd bullet under design goals.  Since pt_BR is a default content locale, all of its content can safely be obtained from "pt".  Also see https://github.com/unicode-cldr/cldr-core/blob/master/defaultContent.json, which contains the list of default content locales in cldr.
